### PR TITLE
Small improvements

### PR DESCRIPTION
**Pull request by atrakic**
While testing test TFs and make sure we dont hit: https://github.com/terraform-providers/terraform-provider-aws/pull/6544. YMMV

### CODE REVIEW

**Comment by atrakic** [comment]
Aah I see, Travis complains "terraform: command not found" :/

**Comment by atrakic** [comment]
Ehm, this doesnt work either: @cd $(AWS_DIR) && $(shell docker run --rm -it --entrypoint bash -w '/mnt' -v $$(pwd):/mnt r.j3ss.co/terraform -c "terraform validate -check-variables=false . && echo '[OK] terraform')

**Comment by atrakic** [comment]
Fixed :)

**Comment by jessfraz** [comment]
thanks!

**Pull request merged**
